import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

export const metadata = {
  metadataBase: new URL("https://bbnsk.vercel.app"), 
  title: "Bbnsk Art Universe — Anastasia Babanska | Art & Piano",
  description:
    "The artistic universe of Anastasia Babanska — painter and composer. Piano music for films and concerts, surreal and mythological oil paintings in the style of Van Gogh. Emotional, cinematic, and spiritual art.",
  keywords: [

    // ENGLISH
    // Main identity
    "Anastasia Babanska",
    "Ukrainian composer",
    "French composer",
    "Bbnsk Art Universe",
    "piano music",
    "film composer",
    "art gallery",
    "surrealism art",
    "oil paintings",
    "Van Gogh style",
    "mythological art",
    "emotional music",
    "ambient piano",
    "modern surrealism",
    "art curator",
    "art dealer",
    "art exhibitions",
    "piano for cinema",
    "piano concerts",
    "French contemporary artist",
    "Ukrainian painter",
    "Anastasiia Babanska artist",
    "Anastasiia Babanska composer",
    "Anastasiia Babanska pianist",
    "Anastasiia Babanska painter",
    "Ukrainian artist in France",
    "French-Ukrainian composer",
    "female artist Paris",
    "female composer Europe",

    // Music & composition
    "piano music",
    "cinematic piano",
    "ambient piano music",
    "emotional piano compositions",
    "modern piano artist",
    "piano for film",
    "film composer",
    "soundtrack music",
    "music for exhibitions",
    "melancholic piano",
    "dark ambient piano",
    "neo-classical music",
    "music for meditation",
    "instrumental music artist",
    "piano composer contemporary",
    "post classical music",

    // Painting & visual art
    "oil paintings",
    "contemporary surrealism",
    "mythological art",
    "symbolism art",
    "Van Gogh inspired",
    "dreamlike painting",
    "surreal impressionism",
    "emotional painting",
    "cosmic art",
    "fantasy painting",
    "female surrealist painter",
    "visionary art",
    "modern art Paris",
    "modern Ukrainian art",
    "art for collectors",
    "art for galleries",

    // Professional context
    "art exhibitions Paris",
    "art curator",
    "art dealer",
    "gallery representation",
    "film music composer",
    "artistic collaborations",
    "visual music projects",
    "multimedia artist",
    "artist residency France",
    "art for cinema",
    "art for stage",
    "art portfolio",
    "emerging contemporary artist",

    // Mood & themes
    "melancholic art",
    "mystical painting",
    "spiritual art",
    "existential art",
    "modern romanticism",
    "emotive soundscapes",
    "visual poetry",
    "dream art",
    "fantasy surrealism",
    "cosmic piano",
    "music of the soul",
    "art of silence",
    "light and shadow art",

    //FRENCH
    "Anastasia Babanska",
    "Bbnsk Art Universe",
    "Compositeur ukrainien",
    "Compositeur français",
    "musique de piano",
    "compositrice de film",
    "galerie d'art",
    "art surréaliste",
    "peintures à l'huile",
    "style Van Gogh",
    "art mythologique",
    "musique émotionnelle",
    "piano ambiant",
    "surréalisme moderne",
    "commissaire d'exposition",
    "marchand d'art",
    "expositions d'art",
    "piano pour le cinéma",
    "concerts de piano",
    "artiste contemporaine française",
    "peintre ukrainienne",
    "Anastasiia Babanska artiste",
    "Anastasiia Babanska compositrice",
    "Anastasiia Babanska pianiste",
    "Anastasiia Babanska peintre",
    "artiste ukrainienne en France",
    "compositrice franco-ukrainienne",
    "artiste féminine Paris",
    "compositrice féminine Europe",

    // Musique & composition
    "musique de piano",
    "piano cinématique",
    "musique de piano ambiante",
    "compositions de piano émotionnelles",
    "artiste de piano moderne",
    "piano pour film",
    "compositrice de film",
    "musique de bande sonore",
    "musique pour expositions",
    "piano mélancolique",
    "piano ambiant sombre",
    "musique néo-classique",
    "musique de méditation",
    "artiste de musique instrumentale",
    "compositrice de piano contemporaine",
    "musique post-classique",

    // Peinture & art visuel
    "peintures à l'huile",
    "surréalisme contemporain",
    "art mythologique",
    "art du symbolisme",
    "inspiré de Van Gogh",
    "peinture onirique",
    "impressionnisme surréaliste",
    "peinture émotionnelle",
    "art cosmique",
    "peinture fantastique",
    "peintre surréaliste féminine",
    "art visionnaire",
    "art moderne Paris",
    "art ukrainien moderne",
    "art pour collectionneurs",
    "art pour galeries",

    // Contexte professionnel
    "expositions d'art Paris",
    "commissaire d'exposition",
    "marchand d'art",
    "représentation en galerie",
    "compositrice de musique de film",
    "collaborations artistiques",
    "projets de musique visuelle",
    "artiste multimédia",
    "résidence d'artiste France",
    "art pour le cinéma",
    "art pour la scène",
    "portfolio artistique",
    "artiste contemporaine émergente",

    // Ambiance & thèmes
    "art mélancolique",
    "peinture mystique",
    "art spirituel",
    "art existentiel",
    "romantisme moderne",
    "paysages sonores émotifs",
    "poésie visuelle",
    "art du rêve",
    "surréalisme fantastique",
    "piano cosmique",
    "musique de l'âme",
    "art du silence",
    "art de la lumière et de l'ombre",

    //UKRAINE
    "Анастасія Бабанська",
    "Український композитор",
    "Французький композитор",
    "Bbnsk Art Universe",
    "фортепіанна музика",
    "композиторка фільмів",
    "артгалерея",
    "сюрреалістичне мистецтво",
    "олійні картини",
    "стиль Ван Гога",
    "міфологічне мистецтво",
    "емоційна музика",
    "ембієнт фортепіано",
    "сучасний сюрреалізм",
    "куратор мистецтва",
    "артдилер",
    "виставки мистецтва",
    "фортепіано для кіно",
    "фортепіанні концерти",
    "сучасна французька художниця",
    "українська художниця",
    "Анастасія Бабанська художниця",
    "Анастасія Бабанська композиторка",
    "Анастасія Бабанська піаністка",
    "Анастасія Бабанська живописиця",
    "українська художниця у Франції",
    "франко-українська композиторка",
    "жінка-художниця Париж",
    "жінка-композиторка Європа",

    // Музика та композиція
    "фортепіанна музика",
    "кінематографічне фортепіано",
    "ембієнт музика для фортепіано",
    "емоційні фортепіанні композиції",
    "сучасна фортепіанна артистка",
    "фортепіано для фільму",
    "композиторка кіно",
    "саундтрек музика",
    "музика для виставок",
    "меланхолічне фортепіано",
    "темний ембієнт",
    "неокласична музика",
    "музика для медитації",
    "інструментальна артистка",
    "сучасна композиторка фортепіано",
    "посткласична музика",

    // Живопис і візуальне мистецтво
    "олійні картини",
    "сучасний сюрреалізм",
    "міфологічне мистецтво",
    "символізм у мистецтві",
    "натхнення Ван Гогом",
    "сновидна живопис",
    "сюрреалістичний імпресіонізм",
    "емоційний живопис",
    "космічне мистецтво",
    "фантазійний живопис",
    "жіноча сюрреалістка",
    "візіонерське мистецтво",
    "сучасне мистецтво Париж",
    "сучасне українське мистецтво",
    "мистецтво для колекціонерів",
    "мистецтво для галерей",

    // Професійний контекст
    "виставки мистецтва Париж",
    "куратор мистецтва",
    "артдилер",
    "галерейне представництво",
    "композиторка фільмової музики",
    "творчі колаборації",
    "візуально-музичні проєкти",
    "мультимедійна артистка",
    "артрезиденція Франція",
    "мистецтво для кіно",
    "мистецтво для сцени",
    "артпортфоліо",
    "сучасна молода художниця",

    // Настрій і теми
    "меланхолічне мистецтво",
    "містичний живопис",
    "духовне мистецтво",
    "екзистенційне мистецтво",
    "сучасний романтизм",
    "емоційні звукові пейзажі",
    "візуальна поезія",
    "мистецтво снів",
    "фантастичний сюрреалізм",
    "космічне фортепіано",
    "музика душі",
    "мистецтво тиші",
    "світло і тінь у мистецтві",


    //DEUTSCH
    "Anastasia Babanska",
    "Französischer Komponist",
    "Ukrainischer Komponist",
    "Bbnsk Art Universe",
    "Klaviermusik",
    "Filmkomponistin",
    "Kunstgalerie",
    "surrealistische Kunst",
    "Ölgemälde",
    "Van-Gogh-Stil",
    "mythologische Kunst",
    "emotionale Musik",
    "Ambient-Klavier",
    "moderner Surrealismus",
    "Kuratorin",
    "Kunsthändlerin",
    "Kunstausstellungen",
    "Klavier für Kino",
    "Klavierkonzerte",
    "zeitgenössische französische Künstlerin",
    "ukrainische Malerin",
    "Anastasiia Babanska Künstlerin",
    "Anastasiia Babanska Komponistin",
    "Anastasiia Babanska Pianistin",
    "Anastasiia Babanska Malerin",
    "ukrainische Künstlerin in Frankreich",
    "französisch-ukrainische Komponistin",
    "weibliche Künstlerin Paris",
    "weibliche Komponistin Europa",

    // Musik & Komposition
    "Klaviermusik",
    "filmisches Klavier",
    "Ambient-Klaviermusik",
    "emotionale Klavierkompositionen",
    "moderne Klavierkünstlerin",
    "Klavier für Film",
    "Filmkomponistin",
    "Soundtrack-Musik",
    "Musik für Ausstellungen",
    "melancholisches Klavier",
    "dunkles Ambient-Klavier",
    "neoklassische Musik",
    "Meditationsmusik",
    "instrumentale Künstlerin",
    "zeitgenössische Klavierkomponistin",
    "postklassische Musik",

    // Malerei & visuelle Kunst
    "Ölgemälde",
    "zeitgenössischer Surrealismus",
    "mythologische Kunst",
    "symbolistische Kunst",
    "inspiriert von Van Gogh",
    "traumhafte Malerei",
    "surrealer Impressionismus",
    "emotionale Malerei",
    "kosmische Kunst",
    "fantastische Malerei",
    "weibliche surrealistische Malerin",
    "visionäre Kunst",
    "moderne Kunst Paris",
    "moderne ukrainische Kunst",
    "Kunst für Sammler",
    "Kunst für Galerien",

    // Beruflicher Kontext
    "Kunstausstellungen Paris",
    "Kuratorin",
    "Kunsthändlerin",
    "Galerievertretung",
    "Filmkomponistin",
    "künstlerische Kooperationen",
    "visuelle Musikprojekte",
    "Multimedia-Künstlerin",
    "Künstlerresidenz Frankreich",
    "Kunst für Kino",
    "Kunst für Bühne",
    "Kunstportfolio",
    "aufstrebende zeitgenössische Künstlerin",

    // Stimmung & Themen
    "melancholische Kunst",
    "mystische Malerei",
    "spirituelle Kunst",
    "existenzielle Kunst",
    "moderner Romantizismus",
    "emotionale Klanglandschaften",
    "visuelle Poesie",
    "Traumkunst",
    "fantastischer Surrealismus",
    "kosmisches Klavier",
    "Musik der Seele",
    "Kunst der Stille",
    "Licht- und Schattenkunst",


  ],
  openGraph: {
    title: "Bbnsk Art Universe — Anastasia Babanska",
    description:
      "Official art and music portfolio of Anastasia Babanska. Piano, painting, and surreal art in motion.",
    url: "https://bbnsk.vercel.app",
    siteName: "Bbnsk Art Universe",
    images: [
      {
        url: "/preview.jpg", 
        width: 1200,
        height: 630,
        alt: "Anastasia Babanska Art & Piano",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Bbnsk Art Universe — Anastasia Babanska",
    description:
      "Discover the universe of Anastasia Babanska — surreal painter & piano composer.",
    images: ["/preview.jpg"],
  },
  icons: {
    icon: "/favicon.png",
  },
  alternates: {
    canonical: "https://bbnsk.vercel.app",

  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>

        {/* analytics */}
        <script defer src="https://cloud.umami.is/script.js" data-website-id="a72518d0-80fc-4da8-8412-3f90ef83a9b3"></script>

        {/* Schema.org structured data for Google */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Person",
              "name": "Anastasia Babanska",
              "alternateName": "Bbnsk",
              "url": "https://bbnsk.vercel.app",
              "image": "https://bbnsk.vercel.app/preview.jpg",
              "jobTitle": "Artist & Composer",
              "description":
                "Anastasia Babanska — multidisciplinary artist and pianist based in France. Her works combine surrealism, sound, and emotion.",
              "address": {
                "@type": "PostalAddress",
                "addressCountry": "France",
              },
              "sameAs": [
                "https://www.instagram.com/bbnsk.art",
                "https://www.youtube.com/AnastasiaBabanska",
                "https://soundcloud.com/anastasia-babanska",
                "https://open.spotify.com/artist/70DqE4HUO60Ra1sBZztRIW",
                "https://music.apple.com/za/artist/anastasia-babanska/1790922079"
              ],
            }),
          }}
        />
      </head>
      <body style={{ margin: 0, padding: 0, overflowX: "hidden" }}>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
